version: "3.9"

services:
  app:
    build: .
    container_name: demo-app
    ports:
      - "8080:5000"
    networks:
      - observability
    labels:
      - "logging=true"
    environment:
      - GRAFANA_CLOUD_USERNAME="1332621"
      - GRAFANA_CLOUD_API_KEY=glc_eyJvIjoiMTQ5NTkzNSIsIm4iOiJzdGFjay0xMzMyNjIxLWludGVncmF0aW9uLXRlc3RvdGxwLXRlc3RvdGxwIiwiayI6Inc4N0NUdldFOUtSVTR6OThpVHYwNFE5NCIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
  alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./alloy-config.alloy:/etc/alloy/config.alloy
    networks:
      - observability
    ports:
      - "4318:4318"
      - "4317:4317"

networks:
  observability:
    driver: bridge